services:
  app_24bet:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_custom_network
    environment:
      DB_URL: jdbc:postgresql://149.50.142.217:5432/db_casino
      DB_USER_NAME: postgres
      DB_PASSWORD: 24bet
      TZ: Etc/GMT+6
    restart: always

  frontend:
    build:
      context: frontend/web
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app_24bet
    volumes:
      - ./frontend/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - VITE_API_BASE_URL=https://24bet.mx/24bet
    networks:
      - my_custom_network

networks:
  my_custom_network:
    driver: bridge
